### ISSUE TITLE
Quiz needs some work

### ISSUE THREAD

**Issue by kode-tiki** [learn-co-curriculum/fe-quiz-05#10]
The answer to question 8 is incorrect. It should be the second answer.

Also, I don't recall the topics of questions 4 and 6 being covered in the material. Maybe I missed something, or maybe they should be changed.

**Comment by ga-be** [comment]
@pletcher – Just submitted a pull request that I believe fixes all outstanding problems with this quiz, including the above-mentioned.

**Comment by pletcher** [comment]
Closed with https://github.com/learn-co-curriculum/fe-quiz-05/commit/902154b9e70679089801444397e88574f447f5fa
