### ISSUE TITLE
The answer were selected and quiz was marked completed

### ISSUE THREAD

**Issue by ayesha-x-ansari** [learn-co-curriculum/fe-quiz-05#15]
Hello,
I notice when I got to this quiz that some of the answers were already selected on its own while some were not and quiz was marked completed. I tried refreshing as well as uploading the quiz but nothing worked. I wanted to select my own answers but it stopped me from doing so. As a result I left it as is and answered the few that were left unanswered and proceeded to press the "I am done" button.

Please look into it and see if anyone else experienced the same issue.

Thanks 

Ayesha

**Comment by maxwellbenton** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
